### ISSUE TITLE
why is it incompatible with lithosphere?

### ISSUE THREAD

**Issue by VaporeonScripts** [Darsenia/woodlands#2] opened 2024-11-16 14:12 UTC
neoforge 1.21.1 .79

and would there be a way to fix this incompatibility?

**Comment by Darsenia** [comment] 2024-11-18 13:17
Not _officially_. Both mods use the same data-based methods to do stuff. You can read the same thing on the Litosphere's page:

_`Most worldgen mods (like Biomes O' Plenty, Nature's Spirit, ...) should be perfectly compatible, but lithosphere changes the deafult noise_settings so worldgen datapacks that change the overworld will be incompatible.

Datapacks that change the noise_settings files can be made compatible by changing their noise_settings to refer to Lithosphere's final_density.`_

_Soo. techniacally, there is an easy way to make them somehow compatible: remove "noise_settings" from the Woodlands mod at all. I just tested it and it worked (extremely laggy though). But I wouldn't do this officially, because it ruins Woodlands' original look. 
If you want to do so, open the Woodlands .jar with 7zip and go to data/minecraft/worldgen and delete "noise_settings" folder. This will remove every ground-cover change Woodlands makes but the mods would work together. The biomes will not look exactly as intended._

And! The more important thing is: will the result be Litosphere landscape with Woodlands biomes? I'm not sure :-D Both mods change the overworld dimension as is, so the result of their partial compatibility will be very questionable. For example with some other data-based mods Woodlands work, but completely takes over their settings, or it could be the other way around.

**Closed as completed** 2024-11-18 13:30 UTC
Labels: wontfix
